PREFIX = mtapp
IANA_URL = https://www.iana.org/assignments/media-types/media-types.xhtml
REGISTRY_ID = application audio font image message model \
              multipart text video

include ../../../gnu-make/common.mk
