MODULE = iana-dns-class-rr-type
PREFIX = dnsct
IANA_URL = https://www.iana.org/assignments/dns-parameters/dns-parameters.xml
REGISTRY_ID = dns-parameters-2 dns-parameters-4

include ../gnu-make/common.mk
